// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sample_z_cpp
arma::vec sample_z_cpp(arma::vec psi, arma::vec p, arma::mat k_s);
RcppExport SEXP _FastOccupancy_sample_z_cpp(SEXP psiSEXP, SEXP pSEXP, SEXP k_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type k_s(k_sSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_z_cpp(psi, p, k_s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastOccupancy_sample_z_cpp", (DL_FUNC) &_FastOccupancy_sample_z_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastOccupancy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
