# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample the occupancies
#' 
#' @param psi Probabilities of presence.
#' @param psi Probabilities of detection.
#' @param k_s Correspondance.
#' @export
sample_z_cpp <- function(psi, p, k_s) {
    .Call('_FastOccupancy_sample_z_cpp', PACKAGE = 'FastOccupancy', psi, p, k_s)
}

